### ISSUE TITLE
拼音版不支持同一字母出现多次的情况

### ISSUE THREAD

**Issue by evan119** [EurusEurus/wordle-crash#1]
In the file [chengyu-pinyin-l4.txt](https://github.com/EurusEurus/wordle-cracker/blob/main/chengyu-pinyin-l4.txt), [filter_word](https://github.com/EurusEurus/wordle-cracker/blob/7466d6b3ea804a67fd08c6d998e6b0cd585488c6/wordle-chengyu.py#L41) has one argument with dictionary type, it doesn't support the case when we take a guess with one letter appears more than once in the entire phrase.

For example, when I guess "xinyoulingxi", both "x" and "i" appear more than once. If we pass `{["x": -1, "i": 0, ... , "x": 1, "i": 1]}`, only the last key-value pairs will be saved. 

It can be fixed by passing a list with tuples (k, v), where k is the letter and v is its status (0/1/-1).

**Comment by AntiKnot** [comment]
> In the file [chengyu-pinyin-l4.txt](https://github.com/EurusEurus/wordle-cracker/blob/main/chengyu-pinyin-l4.txt), [filter_word](https://github.com/EurusEurus/wordle-cracker/blob/7466d6b3ea804a67fd08c6d998e6b0cd585488c6/wordle-chengyu.py#L41) has one argument with dictionary type, it doesn't support the case when we take a guess with one letter appears more than once in the entire phrase.
> 
> For example, when I guess "xinyoulingxi", both "x" and "i" appear more than once. If we pass `{["x": -1, "i": 0, ... , "x": 1, "i": 1]}`, only the last key-value pairs will be saved.
> 
> It can be fixed by passing a list with tuples (k, v), where k is the letter and v is its status (0/1/-1).

Thanks for your advice.
In the beginning, just to reduce the number of options, it will be fixed in time.

**Comment by AntiKnot** [comment]
The resulting response type has been modified, from dict to tuple.

The grammatical errors have been fixed, but there are still problems with the rules.

The rules of wordle pinyin are not exactly the same as wordle, the validation rules of each word are independent, like letter 'i' in 1st word volue -1, letter 'i' in 2st word maybe 1.

will be fixed next.

/cc @evan119
